-- Insert data into genders table
INSERT INTO genders (gender) VALUES ('Male');
INSERT INTO genders (gender) VALUES ('Female');
INSERT INTO genders (gender) VALUES ('Non-binary');
INSERT INTO genders (gender) VALUES ('Other');
INSERT INTO genders (gender) VALUES ('Prefer not to say');
INSERT INTO genders (gender) VALUES ('Genderqueer');
INSERT INTO genders (gender) VALUES ('Two-Spirit');
INSERT INTO genders (gender) VALUES ('Agender');
INSERT INTO genders (gender) VALUES ('Bigender');
INSERT INTO genders (gender) VALUES ('Pangender');

-- Insert data into users table
INSERT INTO users (name, surname, country, fk_GENDERid) VALUES ('John', 'Doe', 'USA', 1);
INSERT INTO users (name, surname, country, fk_GENDERid) VALUES ('Jane', 'Smith', 'UK', 2);
INSERT INTO users (name, surname, country, fk_GENDERid) VALUES ('Alex', 'Johnson', 'Canada', 3);
INSERT INTO users (name, surname, country, fk_GENDERid) VALUES ('Emily', 'Davis', 'Australia', 2);
INSERT INTO users (name, surname, country, fk_GENDERid) VALUES ('Michael', 'Brown', 'New Zealand', 1);
INSERT INTO users (name, surname, country, fk_GENDERid) VALUES ('Sarah', 'Miller', 'Ireland', 2);
INSERT INTO users (name, surname, country, fk_GENDERid) VALUES ('Chris', 'Wilson', 'USA', 4);
INSERT INTO users (name, surname, country, fk_GENDERid) VALUES ('Pat', 'Taylor', 'Canada', 5);
INSERT INTO users (name, surname, country, fk_GENDERid) VALUES ('Jordan', 'Anderson', 'UK', 6);
INSERT INTO users (name, surname, country, fk_GENDERid) VALUES ('Morgan', 'Thomas', 'Australia', 7);

-- Insert data into courses table
INSERT INTO courses (name, approximate_duration, overview, price) VALUES ('Introduction to Programming', 30, 'Learn the basics of programming.', 49.99);
INSERT INTO courses (name, approximate_duration, overview, price) VALUES ('Advanced Databases', 45, 'Deep dive into database management systems.', 99.99);
INSERT INTO courses (name, approximate_duration, overview, price) VALUES ('Web Development', 40, 'Full-stack web development course.', 79.99);
INSERT INTO courses (name, approximate_duration, overview, price) VALUES ('Machine Learning', 50, 'Comprehensive machine learning course.', 119.99);
INSERT INTO courses (name, approximate_duration, overview, price) VALUES ('Data Science', 60, 'Complete data science bootcamp.', 129.99);
INSERT INTO courses (name, approximate_duration, overview, price) VALUES ('Cybersecurity', 35, 'Learn how to protect systems and data.', 89.99);
INSERT INTO courses (name, approximate_duration, overview, price) VALUES ('Cloud Computing', 55, 'Introduction to cloud services.', 109.99);
INSERT INTO courses (name, approximate_duration, overview, price) VALUES ('Mobile App Development', 45, 'Create mobile applications from scratch.', 99.99);
INSERT INTO courses (name, approximate_duration, overview, price) VALUES ('DevOps Practices', 50, 'Learn DevOps methodologies and practices.', 119.99);
INSERT INTO courses (name, approximate_duration, overview, price) VALUES ('Blockchain Technology', 60, 'Understanding blockchain and its applications.', 129.99);

-- Insert data into lectures table
INSERT INTO lectures (title, fk_COURSEid) VALUES ('Programming Basics', 1);
INSERT INTO lectures (title, fk_COURSEid) VALUES ('Control Structures', 1);
INSERT INTO lectures (title, fk_COURSEid) VALUES ('Database Design', 2);
INSERT INTO lectures (title, fk_COURSEid) VALUES ('SQL Queries', 2);
INSERT INTO lectures (title, fk_COURSEid) VALUES ('HTML & CSS', 3);
INSERT INTO lectures (title, fk_COURSEid) VALUES ('JavaScript Fundamentals', 3);
INSERT INTO lectures (title, fk_COURSEid) VALUES ('Introduction to ML', 4);
INSERT INTO lectures (title, fk_COURSEid) VALUES ('Supervised Learning', 4);
INSERT INTO lectures (title, fk_COURSEid) VALUES ('Data Analysis', 5);
INSERT INTO lectures (title, fk_COURSEid) VALUES ('Visualization', 5);

-- Insert data into user_lectures table
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (1, 1, '2023-01-01', 1, 1);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (0, 0, '2023-01-05', 2, 2);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (1, 0, '2023-02-01', 3, 3);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (0, 1, '2023-02-10', 4, 4);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (1, 1, '2023-03-01', 5, 5);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (0, 0, '2023-03-15', 6, 6);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (1, 0, '2023-04-01', 7, 7);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (0, 1, '2023-04-20', 8, 8);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (1, 1, '2023-05-01', 9, 9);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (0, 0, '2023-05-10', 10, 10);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (1, 1, '2023-06-01', 1, 2);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (0, 0, '2023-06-15', 2, 3);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (1, 0, '2023-07-01', 3, 4);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (0, 1, '2023-07-10', 4, 5);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (1, 1, '2023-08-01', 5, 6);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (0, 0, '2023-08-15', 6, 7);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (1, 0, '2023-09-01', 7, 8);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (0, 1, '2023-09-10', 8, 9);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (1, 1, '2023-10-01', 9, 10);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (0, 0, '2023-10-10', 10, 1);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (1, 1, '2023-11-01', 1, 3);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (0, 0, '2023-11-10', 2, 4);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (1, 0, '2023-12-01', 3, 5);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (0, 1, '2023-12-10', 4, 6);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (1, 1, '2024-01-01', 5, 7);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (0, 0, '2024-01-10', 6, 8);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (1, 0, '2024-02-01', 7, 9);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (0, 1, '2024-02-10', 8, 10);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (1, 1, '2024-03-01', 9, 1);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (0, 0, '2024-03-10', 10, 2);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (1, 1, '2024-04-01', 1, 3);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (0, 0, '2024-04-10', 2, 4);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (1, 0, '2024-05-01', 3, 5);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (0, 1, '2024-05-10', 4, 6);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (1, 1, '2024-06-01', 5, 7);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (0, 0, '2024-06-10', 6, 8);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (1, 0, '2024-07-01', 7, 9);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (0, 1, '2024-07-10', 8, 10);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (1, 1, '2024-08-01', 9, 1);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (0, 0, '2024-08-10', 10, 2);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (1, 1, '2024-09-01', 1, 3);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (0, 0, '2024-09-10', 2, 4);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (1, 0, '2024-10-01', 3, 5);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (0, 1, '2024-10-10', 4, 6);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (1, 1, '2024-11-01', 5, 7);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (0, 0, '2024-11-10', 6, 8);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (1, 0, '2024-12-01', 7, 9);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (0, 1, '2024-12-10', 8, 10);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (1, 1, '2025-01-01', 9, 1);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (0, 0, '2025-01-10', 10, 2);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (1, 1, '2025-02-01', 1, 3);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (0, 0, '2025-02-10', 2, 4);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (1, 0, '2025-03-01', 3, 5);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (0, 1, '2025-03-10', 4, 6);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (1, 1, '2025-04-01', 5, 7);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (0, 0, '2025-04-10', 6, 8);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (1, 0, '2025-05-01', 7, 9);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (0, 1, '2025-05-10', 8, 10);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (1, 1, '2025-06-01', 9, 1);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (0, 0, '2025-06-10', 10, 2);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (1, 1, '2025-07-01', 1, 3);
INSERT INTO user_lectures (is_completed, is_starred, start_date, fk_LECTUREid, fk_USERid) VALUES (0, 0, '2025-07-10', 2, 4);
